url: https://www.byemberandash.com
baseurl: /
# Site settings
title: Ember + Ash
email: natalie@byemberandash.com
description: "A small-press publisher for the tabletop role-playing community. Started by 2 uppity rpg nerds who love to make stuff. (Just Outside) Portland, OR"


# Team names, titles and social links
people:
- name: Natalie Ash
  pic: 1
  position: Publisher
  social:
    - title: twitter
      url: https://twitter.com/thenatalieash

- name: Madeleine Ember
  pic: 2
  position: Publisher
  social:
    - title: twitter
      url: https://twitter.com/madeleineember

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/byemberandash

# Postal address (add as many lines as necessary)
address:
  - line: Portland, OR

# Build settings
markdown: kramdown
permalink: pretty
