title: Ember + Ash TTRPG Publishing
description: > # this means to ignore newlines until "baseurl:"
  Ember + Ash is a small-press publisher in the tabletop role-playing space located just outside Portland, OR.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://wwww.byemberandash.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: @ByEmberAndAsh

# Author Settings
author: Ember + Ash # add your name
author-img: david-freeman.jpg # add your photo
about-author: Ember + Ash is a small-press publisher in the tabletop role-playing space located just outside Portland, OR. # add description
social-twitter: @ByEmberAndAsh
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: natalie@byemberandash.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
